# _config.yml
defaults:
  - scope:
      path: ""
      glob: "projects/**/*.md"
      type: "pages"
    values:
      render_with_liquid: false

  - scope:
      path: ""
      glob: "assignments/**/*.md"
      type: "pages"
    values:
      render_with_liquid: false

  - scope:
      path: ""
      glob: "tutorials/**/*.md"
      type: "pages"
    values:
      render_with_liquid: false

# Optional: also catch any .twig anywhere
  - scope:
      path: ""
      glob: "**/*.twig"
      type: "pages"
    values:
      render_with_liquid: false
